import { Injectable, Logger } from "@nestjs/common";
import { DatabaseService } from "./database.service";
import { JobRecord, JobService } from "./job.service";
import { DevelopmentMediaProvider, EmbeddingProviderService, GitRepositoryProvider } from "./providers";
import { StorageService } from "./storage.service";

@Injectable()
export class JobWorker {
  private readonly logger = new Logger(JobWorker.name);
  private stopping = false;
  constructor(private readonly jobs:JobService, private readonly database:DatabaseService, private readonly repo:GitRepositoryProvider, private readonly embeddings:EmbeddingProviderService, private readonly media:DevelopmentMediaProvider, private readonly storage:StorageService) {}
  stop(){this.stopping=true;}
  async run(once=false){const tenant=process.env.AIOPS_TENANT_ID;if(!tenant)throw new Error("AIOPS_TENANT_ID is required for worker execution.");const workerId=process.env.AIOPS_WORKER_ID??`worker-${process.pid}`;while(!this.stopping){await this.jobs.stale(tenant);const job=await this.jobs.claim(tenant,workerId);if(job)await this.process(job);else if(once)break;else await new Promise(resolve=>setTimeout(resolve,Number(process.env.AIOPS_WORKER_POLL_MS??1000)));}}
  private async process(job:JobRecord){try{switch(job.kind){case "repository.index":await this.repository(job);break;case "knowledge.ingest":await this.knowledge(job);break;case "workflow.execute":await this.workflow(job);break;default:if(job.kind.startsWith("media."))await this.mediaJob(job);else throw new Error("JOB_TYPE_UNSUPPORTED");}await this.jobs.complete(job.workspace_id,job.id);}catch(error){const raw=error instanceof Error?error.message:"JOB_FAILED";const code=raw.split(":")[0].slice(0,80);await this.jobs.fail(job.workspace_id,job.id,code,safeMessage(code),isRetryable(code));}}
  private async repository(job:JobRecord){const result=await this.database.withTenant(job.workspace_id,async client=>{const row=await client.query<{repository_url:string;default_branch:string;provider:string}>("SELECT repository_url,default_branch,provider FROM app.codebases WHERE id=$1 AND workspace_id=$2 AND deleted_at IS NULL",[job.resource_id,job.workspace_id]);if(!row.rowCount)throw new Error("REPOSITORY_NOT_FOUND");return row.rows[0];});if(!this.repo.supports(result.provider))throw new Error("REPOSITORY_PROVIDER_UNSUPPORTED");const checkout=await this.repo.checkout(result.repository_url,result.default_branch);try{await this.jobs.heartbeat(job.workspace_id,job.id,60);await this.database.withTenant(job.workspace_id,async client=>{await client.query("UPDATE app.codebases SET status='ready',error_message=NULL,metadata=metadata || $1::jsonb,updated_at=now() WHERE id=$2 AND workspace_id=$3",[JSON.stringify(checkout.metadata),job.resource_id,job.workspace_id]);await client.query("UPDATE app.codebase_scans SET status='succeeded',progress=100,completed_at=now() WHERE codebase_id=$1 AND workspace_id=$2 AND status IN ('pending','running')",[job.resource_id,job.workspace_id]);});}finally{await checkout.cleanup();}}
  private async knowledge(job:JobRecord){const source=await this.database.withTenant(job.workspace_id,async client=>{const result=await client.query<{source_uri:string|null;source_type:string;name:string}>("SELECT source_uri,source_type,name FROM app.knowledge_sources WHERE id=$1 AND workspace_id=$2 AND status<>'deleted'",[job.resource_id,job.workspace_id]);if(!result.rowCount)throw new Error("KNOWLEDGE_SOURCE_NOT_FOUND");return result.rows[0];});let content="";if(source.source_type==="file"&&source.source_uri?.startsWith("storage://"))content=(await this.storage.get(source.source_uri.slice("storage://".length))).toString("utf8");else if(source.source_type==="website")content=(await (await fetch(source.source_uri!,{signal:AbortSignal.timeout(30_000)})).text()).replace(/<[^>]+>/g," ");else throw new Error("KNOWLEDGE_SOURCE_CONTENT_UNAVAILABLE");if(!content.trim())throw new Error("KNOWLEDGE_SOURCE_EMPTY");const chunks=chunk(content);const vectors=await this.embeddings.embed(chunks);await this.database.withTenant(job.workspace_id,async client=>{await client.query("INSERT INTO app.knowledge_documents(id,tenant_id,source_uri,content_hash,mime_type,metadata) VALUES($1,$2,$3,md5($4),'text/plain',$5) ON CONFLICT (id) DO UPDATE SET content_hash=EXCLUDED.content_hash,metadata=EXCLUDED.metadata",[job.resource_id,job.workspace_id,source.source_uri??source.name,content,JSON.stringify({source:source.name})]);await client.query("DELETE FROM app.knowledge_chunks WHERE document_id=$1",[job.resource_id]);for(let index=0;index<chunks.length;index++)await client.query("INSERT INTO app.knowledge_chunks(id,tenant_id,document_id,chunk_index,content,embedding,metadata) VALUES(gen_random_uuid(),$1,$2,$3,$4,$5::vector,$6)",[job.workspace_id,job.resource_id,index,chunks[index],`[${vectors[index].join(",")}]`,JSON.stringify({source:source.name,chunk:index,model:this.embeddings.model})]);await client.query("UPDATE app.knowledge_sources SET status='ready',error_message=NULL,updated_at=now() WHERE id=$1 AND workspace_id=$2",[job.resource_id,job.workspace_id]);});}
  private async mediaJob(job:JobRecord){const mediaJob=await this.database.withTenant(job.workspace_id,async client=>{const result=await client.query<{kind:string}>("SELECT kind FROM app.media_jobs WHERE id=$1 AND workspace_id=$2",[job.resource_id,job.workspace_id]);if(!result.rowCount)throw new Error("MEDIA_JOB_NOT_FOUND");return result.rows[0];});const submitted=await this.media.submit(mediaJob.kind);const result=await this.media.poll(submitted.providerJobId);if(result.status!=="succeeded"||!result.output)throw new Error(result.error??"MEDIA_OUTPUT_MISSING");const key=`${job.workspace_id}/media/${job.resource_id}/output`;await this.storage.put(key,result.output,result.contentType??"application/octet-stream");await this.database.withTenant(job.workspace_id,async client=>{const asset=await client.query("INSERT INTO app.media_assets(workspace_id,name,storage_key,mime_type,size_bytes,status,metadata) VALUES($1,$2,$3,$4,$5,'ready',$6) RETURNING id",[job.workspace_id,`${mediaJob.kind} output`,key,result.contentType??"application/octet-stream",result.output.length,JSON.stringify({providerJobId:submitted.providerJobId})]);await client.query("UPDATE app.media_jobs SET status='succeeded',progress=100,asset_id=$1,completed_at=now() WHERE id=$2 AND workspace_id=$3",[asset.rows[0].id,job.resource_id,job.workspace_id]);});}
  private async workflow(job:JobRecord){const run=await this.database.withTenant(job.workspace_id,async client=>{const result=await client.query<{workflow_id:string;version:number}>("SELECT workflow_id,version FROM app.workflow_runs WHERE id=$1 AND workspace_id=$2 AND status='pending'",[job.resource_id,job.workspace_id]);if(!result.rowCount)throw new Error("WORKFLOW_RUN_NOT_FOUND");return result.rows[0];});const version=await this.database.withTenant(job.workspace_id,async client=>{const result=await client.query<{definition:unknown}>("SELECT definition FROM app.workflow_versions WHERE workflow_id=$1 AND workspace_id=$2 AND version=$3",[run.workflow_id,job.workspace_id,run.version]);if(!result.rowCount)throw new Error("WORKFLOW_VERSION_NOT_FOUND");return result.rows[0];});const definition=version.definition as {steps?:unknown[]};if(Array.isArray(definition.steps)&&definition.steps.some(step=>typeof step!=="object"))throw new Error("WORKFLOW_DEFINITION_INVALID");await this.database.withTenant(job.workspace_id,async client=>{await client.query("UPDATE app.workflow_runs SET status='succeeded',started_at=COALESCE(started_at,now()),completed_at=now() WHERE id=$1 AND workspace_id=$2",[job.resource_id,job.workspace_id]);await client.query("INSERT INTO app.workflow_run_logs(run_id,workspace_id,step_key,status,message) VALUES($1,$2,'workflow','succeeded','Workflow completed with registered steps.')",[job.resource_id,job.workspace_id]);});}
}
function chunk(content:string){const size=1200;const result:string[]=[];for(let index=0;index<content.length;index+=size)result.push(content.slice(index,index+size));return result;}
function safeMessage(code:string){const messages:Record<string,string>={REPOSITORY_AUTH_FAILED:"Repository credentials were rejected.",REPOSITORY_CHECKOUT_FAILED:"The repository could not be fetched.",EMBEDDING_PROVIDER_NOT_CONFIGURED:"Configure an embedding provider before indexing knowledge.",MEDIA_PROVIDER_NOT_CONFIGURED:"Configure a media provider before generating output.",WORKFLOW_TOOL_NOT_CONFIGURED:"A workflow step requires a provider or tool that is not configured."};return messages[code]??"The background operation failed. Review configuration and retry.";}
function isRetryable(code:string){return ["REPOSITORY_CHECKOUT_FAILED","KNOWLEDGE_SOURCE_CONTENT_UNAVAILABLE","MEDIA_PROVIDER_RATE_LIMITED","WORKER_HEARTBEAT_TIMEOUT"].includes(code);}
