import { BadRequestException, Body, Controller, Delete, Get, Headers, NotFoundException, Param, Patch, Post, Query, Req, UseGuards } from "@nestjs/common";
import type { FastifyRequest } from "fastify";
import { DatabaseService } from "./database.service";
import { AuthContext, requireRole, WorkspaceAuthGuard } from "./auth.service";
import { JobService } from "./job.service";
import { StorageService } from "./storage.service";

type RequestWithAuth = FastifyRequest & { auth?: AuthContext };
type BodyMap = Record<string, unknown>;
const pageSize = (value: unknown) => Math.min(Math.max(Number(value) || 25, 1), 100);
const text = (body: BodyMap, key: string, required = false) => { const value = typeof body[key] === "string" ? body[key].trim() : ""; if (required && !value) throw new BadRequestException(`${key} is required.`); return value; };
const uuid = (value: string) => /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);

@Controller()
@UseGuards(WorkspaceAuthGuard)
export class WorkspaceDataController {
  constructor(private readonly database: DatabaseService, private readonly jobService: JobService, private readonly storage: StorageService) {}

  @Get("conversations") async conversations(@Req() req: RequestWithAuth, @Query() query: BodyMap) { return this.list(req, "app.conversations", ["id","title","modality","status","created_at","updated_at"], "title", query); }
  @Post("conversations") async createConversation(@Req() req: RequestWithAuth, @Body() body: BodyMap) { const auth = this.auth(req); const title = text(body, "title") || "New conversation"; const modality = text(body, "modality") || "text"; return this.database.withTenant(auth.tenantId, async client => { const result = await client.query("INSERT INTO app.conversations (workspace_id, title, modality) VALUES ($1,$2,$3) RETURNING *", [auth.tenantId, title.slice(0, 200), modality.slice(0, 32)]); await this.audit(client, auth, "conversation.create", "conversation", result.rows[0].id, "success"); return result.rows[0]; }); }
  @Get("conversations/:id") async conversation(@Req() req: RequestWithAuth, @Param("id") id: string) { return this.one(req, "app.conversations", id); }
  @Patch("conversations/:id") async updateConversation(@Req() req: RequestWithAuth, @Param("id") id: string, @Body() body: BodyMap) { return this.update(req, "app.conversations", id, { title: text(body,"title"), metadata: body.metadata }); }
  @Delete("conversations/:id") async deleteConversation(@Req() req: RequestWithAuth, @Param("id") id: string) { return this.archive(req, "app.conversations", id, "conversation.delete"); }
  @Get("conversations/:id/messages") async messages(@Req() req: RequestWithAuth, @Param("id") id: string, @Query() query: BodyMap) { const auth = this.auth(req); return this.database.withTenant(auth.tenantId, async client => { await this.assertExists(client, "app.conversations", id, auth.tenantId); const result = await client.query("SELECT id, role, content, status, metadata, created_at FROM app.conversation_messages WHERE conversation_id=$1 AND workspace_id=$2 ORDER BY created_at ASC LIMIT $3", [id, auth.tenantId, pageSize(query.pageSize)]); return { items: result.rows, pagination: { page: 1, pageSize: pageSize(query.pageSize), total: result.rowCount ?? result.rows.length, hasNextPage: false } }; }); }
  @Post("conversations/:id/messages") async addMessage(@Req() req: RequestWithAuth, @Param("id") id: string, @Body() body: BodyMap) { const auth = this.auth(req); const content = text(body,"content",true); const role = text(body,"role") || "user"; if (!["user","assistant","system","tool"].includes(role)) throw new BadRequestException("Invalid message role."); return this.database.withTenant(auth.tenantId, async client => { await this.assertExists(client,"app.conversations",id,auth.tenantId); const result = await client.query("INSERT INTO app.conversation_messages (conversation_id,workspace_id,role,content) VALUES ($1,$2,$3,$4) RETURNING *", [id,auth.tenantId,role,content.slice(0,100000)]); await client.query("UPDATE app.conversations SET updated_at=now() WHERE id=$1 AND workspace_id=$2",[id,auth.tenantId]); await this.audit(client,auth,"conversation.message.create","conversation",id,"success"); return result.rows[0]; }); }

  @Get("codebases") async codebases(@Req() req: RequestWithAuth, @Query() query: BodyMap) { return this.list(req,"app.codebases",["id","name","provider","repository_url","default_branch","status","error_message","created_at","updated_at"],"name",query,"deleted_at IS NULL"); }
  @Post("codebases") async createCodebase(@Req() req: RequestWithAuth,@Body() body: BodyMap) { const auth=this.auth(req); const name=text(body,"name",true), repositoryUrl=text(body,"repositoryUrl",true), provider=text(body,"provider")||"generic"; if(!/^https?:\/\//i.test(repositoryUrl)) throw new BadRequestException("repositoryUrl must be an https URL."); return this.database.withTenant(auth.tenantId,async client=>{const result=await client.query("INSERT INTO app.codebases(workspace_id,name,provider,repository_url,default_branch,status) VALUES($1,$2,$3,$4,$5,'pending') RETURNING *",[auth.tenantId,name.slice(0,200),provider.slice(0,32),repositoryUrl,text(body,"defaultBranch")||"main"]); await this.audit(client,auth,"codebase.create","codebase",result.rows[0].id,"success"); return result.rows[0];}); }
  @Get("codebases/:id") async codebase(@Req() req:RequestWithAuth,@Param("id") id:string){return this.one(req,"app.codebases",id,"deleted_at IS NULL");}
  @Patch("codebases/:id") async updateCodebase(@Req() req:RequestWithAuth,@Param("id") id:string,@Body() body:BodyMap){return this.update(req,"app.codebases",id,{name:text(body,"name"),default_branch:text(body,"defaultBranch"),metadata:body.metadata});}
  @Delete("codebases/:id") async deleteCodebase(@Req() req:RequestWithAuth,@Param("id") id:string){return this.archive(req,"app.codebases",id,"codebase.delete");}
  @Post("codebases/:id/index") async indexCodebase(@Req() req:RequestWithAuth,@Param("id") id:string){const auth=this.auth(req);return this.database.withTenant(auth.tenantId,async client=>{await this.assertExists(client,"app.codebases",id,auth.tenantId,"deleted_at IS NULL");const result=await client.query("INSERT INTO app.codebase_scans(codebase_id,workspace_id,status) VALUES($1,$2,'pending') RETURNING *",[id,auth.tenantId]);await client.query("UPDATE app.codebases SET status='indexing',updated_at=now() WHERE id=$1 AND workspace_id=$2",[id,auth.tenantId]);await this.audit(client,auth,"codebase.index","codebase",id,"accepted");return {...result.rows[0],job:await this.jobService.enqueue({workspaceId:auth.tenantId,initiatedBy:auth.subject,kind:"repository.index",resourceType:"codebase",resourceId:id})};});}
  @Get("codebases/:id/scans") async scans(@Req() req:RequestWithAuth,@Param("id") id:string){const auth=this.auth(req);return this.database.withTenant(auth.tenantId,async client=>{await this.assertExists(client,"app.codebases",id,auth.tenantId);const result=await client.query("SELECT * FROM app.codebase_scans WHERE codebase_id=$1 AND workspace_id=$2 ORDER BY created_at DESC LIMIT 100",[id,auth.tenantId]);return {items:result.rows,pagination:{page:1,pageSize:100,total:result.rowCount??result.rows.length,hasNextPage:false}};});}

  @Get("knowledge/collections") async collections(@Req() req:RequestWithAuth,@Query() query:BodyMap){return this.list(req,"app.knowledge_collections",["id","name","description","created_at","updated_at"],"name",query,"deleted_at IS NULL");}
  @Post("knowledge/collections") async createCollection(@Req() req:RequestWithAuth,@Body() body:BodyMap){const auth=this.auth(req);const name=text(body,"name",true);return this.database.withTenant(auth.tenantId,async client=>{const result=await client.query("INSERT INTO app.knowledge_collections(workspace_id,name,description) VALUES($1,$2,$3) RETURNING *",[auth.tenantId,name.slice(0,200),text(body,"description").slice(0,2000)]);await this.audit(client,auth,"knowledge.collection.create","collection",result.rows[0].id,"success");return result.rows[0];});}
  @Get("knowledge/sources") async sources(@Req() req:RequestWithAuth,@Query() query:BodyMap){return this.list(req,"app.knowledge_sources",["id","name","source_type","source_uri","mime_type","size_bytes","status","error_message","collection_id","created_at","updated_at"],"name",query);}
  @Post("knowledge/sources") async createSource(@Req() req:RequestWithAuth,@Body() body:BodyMap){const auth=this.auth(req);const name=text(body,"name",true),sourceType=text(body,"sourceType",true);if(!["file","website","integration"].includes(sourceType))throw new BadRequestException("Unsupported sourceType.");const uri=text(body,"sourceUri");if(sourceType!=="file"&&!/^https:\/\//i.test(uri))throw new BadRequestException("Website and integration sources require an https sourceUri.");return this.database.withTenant(auth.tenantId,async client=>{const result=await client.query("INSERT INTO app.knowledge_sources(workspace_id,name,source_type,source_uri,mime_type,size_bytes,collection_id,status) VALUES($1,$2,$3,$4,$5,$6,$7,'pending') RETURNING *",[auth.tenantId,name.slice(0,200),sourceType,uri||null,text(body,"mimeType")||null,Number(body.sizeBytes)||null,body.collectionId||null]);await this.audit(client,auth,"knowledge.source.create","knowledge_source",result.rows[0].id,"success");return result.rows[0];});}
  @Get("knowledge/sources/:id") async source(@Req() req:RequestWithAuth,@Param("id") id:string){return this.one(req,"app.knowledge_sources",id);}
  @Post("knowledge/sources/:id/index") async indexSource(@Req() req:RequestWithAuth,@Param("id") id:string){const result=await this.setStatus(req,"app.knowledge_sources",id,"indexing","knowledge.source.index");const auth=this.auth(req);return {...result,job:await this.jobService.enqueue({workspaceId:auth.tenantId,initiatedBy:auth.subject,kind:"knowledge.ingest",resourceType:"knowledge_source",resourceId:id})};}
  @Delete("knowledge/sources/:id") async deleteSource(@Req() req:RequestWithAuth,@Param("id") id:string){return this.archive(req,"app.knowledge_sources",id,"knowledge.source.delete","deleted");}
  @Post("knowledge/query") async queryKnowledge(@Req() req:RequestWithAuth,@Body() body:BodyMap){const auth=this.auth(req);const question=text(body,"question",true);return this.database.withTenant(auth.tenantId,async client=>{const result=await client.query("SELECT id,name,status,metadata FROM app.knowledge_sources WHERE workspace_id=$1 AND status='ready' AND (name ILIKE $2 OR source_uri ILIKE $2) ORDER BY updated_at DESC LIMIT 20",[auth.tenantId,`%${question.slice(0,80)}%`]);return {answer:null,citations:result.rows,configuration:{groundingAvailable:result.rows.length>0},message:result.rows.length?"No answer generator is configured; select a cited source to continue.":"No indexed sources match this question."};});}

  @Get("media/assets") async assets(@Req() req:RequestWithAuth,@Query() query:BodyMap){return this.list(req,"app.media_assets",["id","name","mime_type","size_bytes","status","metadata","created_at","updated_at"],"name",query,"status <> 'deleted'");}
  @Post("media/assets") async createAsset(@Req() req:RequestWithAuth,@Body() body:BodyMap){const auth=this.auth(req);const name=text(body,"name",true),key=text(body,"storageKey",true),mime=text(body,"mimeType",true);if(key.includes("..")||key.startsWith("/"))throw new BadRequestException("storageKey must be a tenant-scoped object key.");return this.database.withTenant(auth.tenantId,async client=>{const result=await client.query("INSERT INTO app.media_assets(workspace_id,name,storage_key,mime_type,size_bytes,status,metadata) VALUES($1,$2,$3,$4,$5,'ready',$6) RETURNING id,name,mime_type,size_bytes,status,metadata,created_at,updated_at",[auth.tenantId,name.slice(0,200),key,mime,Math.max(Number(body.sizeBytes)||0,0),body.metadata??{}]);await this.audit(client,auth,"media.asset.create","media_asset",result.rows[0].id,"success");return result.rows[0];});}
  @Get("media/assets/:id") async asset(@Req() req:RequestWithAuth,@Param("id") id:string){const auth=this.auth(req);return this.database.withTenant(auth.tenantId,async client=>{const result=await client.query("SELECT id,name,mime_type,size_bytes,status,metadata,created_at,updated_at FROM app.media_assets WHERE id=$1 AND workspace_id=$2 AND status <> 'deleted'",[id,auth.tenantId]);if(!result.rowCount)throw new NotFoundException("Resource not found.");return result.rows[0];});}
  @Get("media/assets/:id/download-url") async assetUrl(@Req() req:RequestWithAuth,@Param("id") id:string){const auth=this.auth(req);return this.database.withTenant(auth.tenantId,async client=>{const result=await client.query<{storage_key:string}>("SELECT storage_key FROM app.media_assets WHERE id=$1 AND workspace_id=$2 AND status='ready'",[id,auth.tenantId]);if(!result.rowCount)throw new NotFoundException("Asset is not ready.");return {url:await this.storage.signedDownload(result.rows[0].storage_key)};});}
  @Patch("media/assets/:id") async updateAsset(@Req() req:RequestWithAuth,@Param("id") id:string,@Body() body:BodyMap){return this.update(req,"app.media_assets",id,{name:text(body,"name"),metadata:body.metadata});}
  @Delete("media/assets/:id") async deleteAsset(@Req() req:RequestWithAuth,@Param("id") id:string){return this.archive(req,"app.media_assets",id,"media.asset.delete","deleted");}
  @Post("media/generate") async generateMedia(@Req() req:RequestWithAuth,@Body() body:BodyMap){const auth=this.auth(req);const kind=text(body,"kind",true);return this.database.withTenant(auth.tenantId,async client=>{const result=await client.query("INSERT INTO app.media_jobs(workspace_id,kind,status,idempotency_key) VALUES($1,$2,'pending',$3) ON CONFLICT (workspace_id,idempotency_key) DO UPDATE SET kind=EXCLUDED.kind RETURNING *",[auth.tenantId,kind.slice(0,40),text(body,"idempotencyKey")||null]);await this.audit(client,auth,"media.generate","media_job",result.rows[0].id,"accepted");return {...result.rows[0],job:await this.jobService.enqueue({workspaceId:auth.tenantId,initiatedBy:auth.subject,kind:`media.${kind}`,resourceType:"media_job",resourceId:result.rows[0].id,idempotencyKey:text(body,"idempotencyKey")||undefined})};});}
  @Get("media/jobs/:id") async mediaJob(@Req() req:RequestWithAuth,@Param("id") id:string){return this.one(req,"app.media_jobs",id);}

  @Get("workflows") async workflows(@Req() req:RequestWithAuth,@Query() query:BodyMap){return this.list(req,"app.workflows",["id","name","description","status","current_version","created_at","updated_at"],"name",query,"archived_at IS NULL");}
  @Post("workflows") async createWorkflow(@Req() req:RequestWithAuth,@Body() body:BodyMap){const auth=this.auth(req);const name=text(body,"name",true),definition=body.definition??{};if(typeof definition!=="object")throw new BadRequestException("definition must be an object.");return this.database.withTenant(auth.tenantId,async client=>{const workflow=await client.query("INSERT INTO app.workflows(workspace_id,name,description) VALUES($1,$2,$3) RETURNING *",[auth.tenantId,name.slice(0,200),text(body,"description").slice(0,2000)]);await client.query("INSERT INTO app.workflow_versions(workflow_id,workspace_id,version,definition) VALUES($1,$2,1,$3)",[workflow.rows[0].id,auth.tenantId,definition]);await this.audit(client,auth,"workflow.create","workflow",workflow.rows[0].id,"success");return workflow.rows[0];});}
  @Get("workflows/:id") async workflow(@Req() req:RequestWithAuth,@Param("id") id:string){return this.one(req,"app.workflows",id,"archived_at IS NULL");}
  @Patch("workflows/:id") async updateWorkflow(@Req() req:RequestWithAuth,@Param("id") id:string,@Body() body:BodyMap){return this.update(req,"app.workflows",id,{name:text(body,"name"),description:text(body,"description")});}
  @Delete("workflows/:id") async deleteWorkflow(@Req() req:RequestWithAuth,@Param("id") id:string){return this.archive(req,"app.workflows",id,"workflow.archive");}
  @Post("workflows/:id/run") async runWorkflow(@Req() req:RequestWithAuth,@Param("id") id:string,@Headers("idempotency-key") key?:string){const auth=this.auth(req);return this.database.withTenant(auth.tenantId,async client=>{const workflow=await this.assertExists(client,"app.workflows",id,auth.tenantId,"archived_at IS NULL");const result=await client.query("INSERT INTO app.workflow_runs(workflow_id,workspace_id,version,idempotency_key) VALUES($1,$2,$3,$4) ON CONFLICT (workflow_id,idempotency_key) DO UPDATE SET workflow_id=EXCLUDED.workflow_id RETURNING *",[id,auth.tenantId,workflow.current_version,key||null]);await this.audit(client,auth,"workflow.run","workflow",id,"accepted");return {...result.rows[0],job:await this.jobService.enqueue({workspaceId:auth.tenantId,initiatedBy:auth.subject,kind:"workflow.execute",resourceType:"workflow_run",resourceId:result.rows[0].id,idempotencyKey:key||undefined})};});}
  @Get("workflows/:id/runs") async workflowRuns(@Req() req:RequestWithAuth,@Param("id") id:string){const auth=this.auth(req);return this.database.withTenant(auth.tenantId,async client=>{await this.assertExists(client,"app.workflows",id,auth.tenantId);const result=await client.query("SELECT * FROM app.workflow_runs WHERE workflow_id=$1 AND workspace_id=$2 ORDER BY created_at DESC LIMIT 100",[id,auth.tenantId]);return {items:result.rows,pagination:{page:1,pageSize:100,total:result.rowCount??result.rows.length,hasNextPage:false}};});}

  @Get("registry") async registry(@Req() req:RequestWithAuth,@Query() query:BodyMap){return this.list(req,"app.registry_items",["id","name","item_type","status","description","created_at","updated_at"],"name",query);}
  @Post("registry") async createRegistry(@Req() req:RequestWithAuth,@Body() body:BodyMap){const auth=this.auth(req);requireRole(req,["owner","admin","operator"]);const name=text(body,"name",true),itemType=text(body,"itemType",true);return this.database.withTenant(auth.tenantId,async client=>{const result=await client.query("INSERT INTO app.registry_items(workspace_id,name,item_type,description) VALUES($1,$2,$3,$4) RETURNING *",[auth.tenantId,name.slice(0,200),itemType.slice(0,32),text(body,"description").slice(0,2000)]);await this.audit(client,auth,"registry.create","registry_item",result.rows[0].id,"success");return result.rows[0];});}
  @Post("registry/:id/submit") async submitRegistry(@Req() req:RequestWithAuth,@Param("id") id:string){return this.setStatus(req,"app.registry_items",id,"quarantined","registry.submit");}
  @Post("registry/:id/approve") async approveRegistry(@Req() req:RequestWithAuth,@Param("id") id:string){requireRole(req,["owner","admin"]);return this.setStatus(req,"app.registry_items",id,"approved","registry.approve");}
  @Post("registry/:id/reject") async rejectRegistry(@Req() req:RequestWithAuth,@Param("id") id:string,@Body() body:BodyMap){if(!text(body,"reason",true))throw new BadRequestException("reason is required.");requireRole(req,["owner","admin"]);return this.setStatus(req,"app.registry_items",id,"rejected","registry.reject");}
  @Get("approvals") async approvals(@Req() req:RequestWithAuth,@Query() query:BodyMap){return this.list(req,"app.approval_requests",["id","resource_type","resource_id","status","reason","created_at","reviewed_at"],"resource_type",query);}

  @Get("projects") async projects(@Req() req:RequestWithAuth,@Query() query:BodyMap){return this.list(req,"app.projects",["id","slug","display_name","state","created_at","updated_at"],"display_name",query,"true","tenant_id");}
  @Post("projects") async createProject(@Req() req:RequestWithAuth,@Body() body:BodyMap){const auth=this.auth(req);requireRole(req,["owner","admin","operator"]);const name=text(body,"name",true),slug=(text(body,"slug")||name.toLowerCase().replace(/[^a-z0-9]+/g,"-")).replace(/^-|-$/g,"").slice(0,64);if(slug.length<2)throw new BadRequestException("name or slug is too short.");return this.database.withTenant(auth.tenantId,async client=>{const result=await client.query("INSERT INTO app.projects(id,tenant_id,slug,display_name,state) VALUES(gen_random_uuid(),$1,$2,$3,'idle') RETURNING *",[auth.tenantId,slug,name.slice(0,200)]);await this.audit(client,auth,"project.create","project",result.rows[0].id,"success");return result.rows[0];});}
  @Get("projects/:id") async project(@Req() req:RequestWithAuth,@Param("id") id:string){return this.one(req,"app.projects",id,"true","tenant_id");}
  @Patch("projects/:id") async updateProject(@Req() req:RequestWithAuth,@Param("id") id:string,@Body() body:BodyMap){return this.update(req,"app.projects",id,{display_name:text(body,"name"),state:text(body,"state")},"tenant_id");}
  @Post("projects/:id/archive") async archiveProject(@Req() req:RequestWithAuth,@Param("id") id:string){return this.update(req,"app.projects",id,{state:"stopped"},"tenant_id");}

  @Get("operations/audit") async auditEvents(@Req() req:RequestWithAuth,@Query() query:BodyMap){return this.list(req,"app.audit_events",["id","actor_subject","action","resource_type","resource_id","result","request_id","metadata","created_at"],"action",query);}
  @Get("operations/jobs") async jobs(@Req() req:RequestWithAuth,@Query() query:BodyMap){return this.list(req,"app.background_jobs",["id","kind","resource_type","resource_id","status","progress","attempts","error_message","created_at","started_at","completed_at"],"kind",query);}
  @Post("operations/jobs/:id/retry") async retryJob(@Req() req:RequestWithAuth,@Param("id") id:string){requireRole(req,["owner","admin","operator"]);return this.setStatus(req,"app.background_jobs",id,"pending","operation.job.retry");}
  @Post("operations/jobs/:id/cancel") async cancelJob(@Req() req:RequestWithAuth,@Param("id") id:string){requireRole(req,["owner","admin","operator"]);return this.setStatus(req,"app.background_jobs",id,"cancelled","operation.job.cancel");}

  private auth(req:RequestWithAuth){if(!req.auth)throw new NotFoundException("Workspace context unavailable.");return req.auth;}
  private async list(req:RequestWithAuth, table:string, columns:string[], searchColumn:string, query:BodyMap, extra="true", tenantColumn="workspace_id"){const auth=this.auth(req),size=pageSize(query.pageSize),page=Math.max(Number(query.page)||1,1),search=typeof query.search==="string"?query.search.trim().slice(0,100):"";return this.database.withTenant(auth.tenantId,async client=>{const where=[`${tenantColumn} = $1`,extra],values:unknown[]=[auth.tenantId];if(search){values.push(`%${search}%`);where.push(`${searchColumn} ILIKE $${values.length}`);}const count=await client.query(`SELECT count(*)::int AS total FROM ${table} WHERE ${where.join(" AND ")}`,values);values.push(size,(page-1)*size);const result=await client.query(`SELECT ${columns.join(",")} FROM ${table} WHERE ${where.join(" AND ")} ORDER BY updated_at DESC NULLS LAST, created_at DESC LIMIT $${values.length-1} OFFSET $${values.length}`,values);const total=Number(count.rows[0].total);return {items:result.rows,pagination:{page,pageSize:size,total,hasNextPage:page*size<total}};});}
  private async one(req:RequestWithAuth,table:string,id:string,extra="true",tenantColumn="workspace_id"){const auth=this.auth(req);if(!uuid(id))throw new BadRequestException("Invalid resource id.");return this.database.withTenant(auth.tenantId,async client=>{return this.assertExists(client,table,id,auth.tenantId,extra,tenantColumn);});}
  private async update(req:RequestWithAuth,table:string,id:string,values:Record<string,unknown>,tenantColumn="workspace_id"){const auth=this.auth(req);if(!uuid(id))throw new BadRequestException("Invalid resource id.");const entries=Object.entries(values).filter(([,value])=>value!==undefined&&value!=="");if(!entries.length)throw new BadRequestException("No update fields supplied.");return this.database.withTenant(auth.tenantId,async client=>{const sets=entries.map(([key],index)=>`${key === "display_name" ? "display_name" : key}=$${index+2}`).join(",");const result=await client.query(`UPDATE ${table} SET ${sets}, updated_at=now() WHERE id=$1 AND ${tenantColumn}=$${entries.length+2} RETURNING *`,[id,...entries.map(([,value])=>value),auth.tenantId]);if(!result.rowCount)throw new NotFoundException("Resource not found.");await this.audit(client,auth,"resource.update",table,result.rows[0].id,"success");return result.rows[0];});}
  private async archive(req:RequestWithAuth,table:string,id:string,action:string,status="archived"){const auth=this.auth(req);return this.database.withTenant(auth.tenantId,async client=>{const column=table.includes("conversations")?"status":table.includes("projects")?"state":"status";const result=await client.query(`UPDATE ${table} SET ${column}=$1, updated_at=now() WHERE id=$2 AND workspace_id=$3 RETURNING *`,[status,id,auth.tenantId]);if(!result.rowCount)throw new NotFoundException("Resource not found.");await this.audit(client,auth,action,table,result.rows[0].id,"success");return result.rows[0];});}
  private async setStatus(req:RequestWithAuth,table:string,id:string,status:string,action:string){const auth=this.auth(req);return this.database.withTenant(auth.tenantId,async client=>{const result=await client.query(`UPDATE ${table} SET status=$1, updated_at=now() WHERE id=$2 AND workspace_id=$3 RETURNING *`,[status,id,auth.tenantId]);if(!result.rowCount)throw new NotFoundException("Resource not found.");await this.audit(client,auth,action,table,result.rows[0].id,"success");return result.rows[0];});}
  private async assertExists(client: {query: (text:string, values?:unknown[])=>Promise<{rows: any[];rowCount:number|null}>},table:string,id:string,tenantId:string,extra="true",tenantColumn="workspace_id"){const result=await client.query(`SELECT * FROM ${table} WHERE id=$1 AND ${tenantColumn}=$2 AND ${extra} LIMIT 1`,[id,tenantId]);if(!result.rowCount)throw new NotFoundException("Resource not found.");return result.rows[0];}
  private async audit(client: {query: (text:string, values?:unknown[])=>Promise<unknown>},auth:AuthContext,action:string,type:string,id:string,result:string){await client.query("INSERT INTO app.audit_events(workspace_id,actor_subject,action,resource_type,resource_id,result) VALUES($1,$2,$3,$4,$5,$6)",[auth.tenantId,auth.subject,action,type,id,result]);}
}
