import { CorrelationResult, ModelEvidence, ModelState } from "./q-ai.types";

export const clamp = (value: number, min = 0, max = 1) => Math.min(Math.max(Number.isFinite(value) ? value : min, min), max);
export function normalize(values: Record<string, number>): Record<string, number> { const total = Object.values(values).reduce((sum, value) => sum + Math.max(value, 0), 0); if (total <= 0) { const keys = Object.keys(values); return Object.fromEntries(keys.map(key => [key, keys.length ? 1 / keys.length : 0])); } return Object.fromEntries(Object.entries(values).map(([key, value]) => [key, Math.max(value, 0) / total])); }
export function entropy(probabilities: Record<string, number>): number { const values = Object.values(probabilities).filter(value => value > 0); if (values.length < 2) return 0; const h = -values.reduce((sum, value) => sum + value * Math.log(value), 0); return clamp(h / Math.log(values.length)); }
export function routingScore(model: ModelState, weights: Partial<Record<keyof ModelState, number>> = {}): number { const defaults: Record<string, number> = { reliability: .2, accuracy: .2, calibration: .1, latencyEfficiency: .1, costEfficiency: .1, taskFit: .1, domainFit: .1, independence: .05, availability: .05 }; const keys = Object.keys(defaults); const total = keys.reduce((sum, key) => sum + (weights[key as keyof ModelState] ?? defaults[key]), 0); return clamp(keys.reduce((sum, key) => sum + clamp(Number(model[key as keyof ModelState])) * (weights[key as keyof ModelState] ?? defaults[key]), 0) / total); }
export function initialProbabilityField(models: ModelState[]): Record<string, number> { return normalize(Object.fromEntries(models.map(model => [`${model.provider}:${model.modelId}`, routingScore(model)]))); }
function tokens(text: string) { return new Set((text.toLowerCase().match(/[a-z0-9_]{3,}/g) ?? [])); }
function overlap(a: string, b: string) { const left = tokens(a), right = tokens(b); if (!left.size || !right.size) return 0; let common = 0; for (const item of left) if (right.has(item)) common++; return common / Math.max(left.size, right.size); }
export function correlation(evidence: ModelEvidence[]): CorrelationResult { const matrix: Record<string, Record<string, number>> = {}; for (const a of evidence) { matrix[a.model] = {}; for (const b of evidence) matrix[a.model][b.model] = a.model === b.model ? 1 : clamp((a.prediction === b.prediction ? .55 : 0) + .25 * overlap(a.reasoningSummary ?? "", b.reasoningSummary ?? "") + .2 * (1 - Math.abs(a.confidence - b.confidence))); } const effectiveWeights: Record<string, number> = {}; for (const item of evidence) { const others = evidence.filter(other => other.model !== item.model); const meanCorrelation = others.length ? others.reduce((sum, other) => sum + matrix[item.model][other.model], 0) / others.length : 0; effectiveWeights[item.model] = clamp((1 - .6 * meanCorrelation) * item.confidence, .05, 1); } return { matrix, effectiveWeights }; }
export function interference(evidence: ModelEvidence[], weights: Record<string, number>): Record<string, number> { const result: Record<string, number> = {}; for (const item of evidence) { for (const [candidate, probability] of Object.entries(item.probabilities)) { const signed = candidate === item.prediction ? 1 : .35; const amplitude = Math.sqrt(clamp(probability)) * (item.prediction === candidate ? signed : -signed); result[candidate] = (result[candidate] ?? 0) + amplitude * (weights[item.model] ?? 1); } } return normalize(Object.fromEntries(Object.entries(result).map(([key, value]) => [key, value * value]))); }
export function bayesianFusion(evidence: ModelEvidence[], weights: Record<string, number>, prior: Record<string, number> = {}): Record<string, number> { const candidates = new Set(Object.keys(prior)); evidence.forEach(item => Object.keys(item.probabilities).forEach(candidate => candidates.add(candidate))); const logs: Record<string, number> = {}; for (const candidate of candidates) { logs[candidate] = Math.log(Math.max(prior[candidate] ?? 1 / Math.max(candidates.size, 1), 1e-12)); for (const item of evidence) logs[candidate] += (weights[item.model] ?? 1) * Math.log(Math.max(item.probabilities[candidate] ?? 1e-6, 1e-6)); } const max = Math.max(...Object.values(logs), 0); return normalize(Object.fromEntries(Object.entries(logs).map(([key, value]) => [key, Math.exp(value - max)]))); }
export function stability(evidence: ModelEvidence[], full: Record<string, number>): number { if (evidence.length < 2) return .5; const winner = Object.entries(full).sort((a, b) => b[1] - a[1])[0]?.[0]; if (!winner) return 0; let stable = 0; for (const item of evidence) { const remaining = evidence.filter(other => other.model !== item.model); const result = bayesianFusion(remaining, Object.fromEntries(remaining.map(other => [other.model, 1]))); if (Object.entries(result).sort((a, b) => b[1] - a[1])[0]?.[0] === winner) stable++; } return stable / evidence.length; }
